server:
  port: 2000
  max-http-header-size: 200KB
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      group-id: cotis
  #      auto-offset-reset: earliest
  #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  security:
    oauth2:
      resourceserver:
        opaque:
          #          introspection-uri: https://keycloackdev.afrilins.net/auth/realms/secuGlobal/protocol/openid-connect/token/introspect
          introspection-uri: http://localhost:9080/auth/realms/secuGlobal/protocol/openid-connect/token/introspect
          introspection-client-id: gestionenquete
          introspection-client-secret: 6f7f977f-a7df-47b8-86ec-d357c6b0fe35
  #          introspection-client-secret: b66f47fa-66c6-46b4-b968-334300fef20a

  #testWhileIdle: true # Keep the connection alive if idle for a long time (needed in production)
  # JPA / HIBERNATE
  jpa:
    show-sql: true #Show or not log for each sql query
    hibernate:
      ddl-auto: create  #schema  will be automatically created afresh for every start of application Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
    #Naming strategy
    naming:
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      # Allows Hibernate to generate SQL optimized for a particular DBMS
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

  liquibase:
    change-log: config/liquibase/master.xml
  application:
    name: gestionenquete
  profiles:
    active: dev
  data:
    web:
      pageable:
        default-page-size: 200000
        max-page-size: 200000
    rest:
      default-page-size: 200000
      max-page-size: 200000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include:  '*'
keycloak:
  realm: secuGlobal
  auth-server-url: http://localhost:9080/auth/
  ssl-required: external
  resource: gestionenquete
  bearer-only: true
  #  verify-token-audience: true
  credentials:
    secret: 6f7f977f-a7df-47b8-86ec-d357c6b0fe35
      # policy-enforcer-config:
      #  paths:
      #   - enforcementMode: DISABLED
      #    path: /v1/dmz/*
      # enforcement-mode: ENFORCING
      # lazy-load-paths: true
      # http-method-as-scope: true
      # on-deny-redirect-to: /403

      #security-constraints:
    # - auth-roles:
    #    - "*"
    # security-collections:
    #  - name:
    #   patterns:
    #    - /v1/api/*
config-db:
  urldb: jdbc:oracle:thin:@//localhost:1521/xe
  password_asi: gestionenquete
  username_asi: gestionenquete
  username_param: parametrageglobal
  password_param: parametrageglobal
  driver: oracle.jdbc.driver.OracleDriver
info:
  description: gestionenquete
  version: v1
feign:
  circuitbreaker:
    enabled: false