CREATE SCHEMA IF NOT EXISTS PARAMETRAGEGLOBAL;
CREATE SCHEMA IF NOT EXISTS APROSTOCKIMMO;
create schema if not exists APROSTOCKIMMO;
create  table IF NOT EXISTS  PARAMETRAGEGLOBAL.PARAMETRAGEGLOBAL_CENTRE_DE_GESTION(ID int PRIMARY KEY NOT NULL, code varchar(255), libelle varchar(255));
create  table IF NOT EXISTS   PARAMETRAGEGLOBAL.PARAMETRAGEGLOBAL_ORGANIGRAMME(ID int PRIMARY KEY NOT NULL , code varchar(255), libelle varchar(255));
CREATE TABLE IF NOT EXISTS  APROSTOCKIMMO.DEMANDE_EXPRESSION_DE_BESOIN
(	ID NUMBER(19,0),
     DATE_CREATION TIMESTAMP (6),
     DATE_MODIFICATION VARCHAR2(255 CHAR),
     DATE_DEMANDE DATE,
     DATE_LIVRAISON DATE,
     DEMANDEUR VARCHAR2(255 CHAR),
     DESCRIPTION VARCHAR2(255 CHAR),
     LIBELLE VARCHAR2(255 CHAR),
     MODE_EXPRESSION VARCHAR2(255 CHAR),
     ANNULATION VARCHAR2(255 CHAR),
     NATURE_DEMANDE NUMBER(10,0),
     NUMERO VARCHAR2(255 CHAR),
     NUMERO_DOSSIER VARCHAR2(255 CHAR),
     DATE_LIVRAISON_SOUHAITE DATE,
     CENTRE_DE_GESTION NUMBER(19,0),
     EXERCICE_ID NUMBER(19,0),
     UTILISATEUR_CREATION NUMBER(19,0),
     UTILISATEUR_MODIFICATION NUMBER(19,0),
     CENTRE_DE_GESTION_ID NUMBER(19,0),
     DEMANDE_DE_BIEN_ID NUMBER(19,0),
     DEMANDE_DE_SERVICE_ID NUMBER(19,0),
     ORGANIGRAMME_ID NUMBER(19,0),
     URGENCE_ID NUMBER(19,0),
     USER_ANNULER_ID NUMBER(19,0),
     DATE_ANNULATION DATE,
     DATE_VALIDATION DATE,
     UTILISATEUR_ANNULATION_ID NUMBER(19,0),
     UTILISATEUR_VALIDATION_ID NUMBER(19,0),
     ETAT_DEMANDE_ID NUMBER(19,0)
);
CREATE TABLE IF NOT EXISTS APROSTOCKIMMO.PARAMETRAGE_URGENCE
(	ID NUMBER(19,0),
     CODE VARCHAR2(255 CHAR),
     LIBELLE VARCHAR2(255 CHAR)
);


CREATE TABLE IF NOT EXISTS APROSTOCKIMMO.PARAMETRAGE_ARTICLE
(	ID NUMBER(19,0),
    CODE VARCHAR2(255 CHAR),
    LIBELLE VARCHAR2(255 CHAR),
    TYPE_ARTICLE VARCHAR(255 CHAR),
    famille_prestation_id NUMBER(19,0),
    unites_article_ID NUMBER(19,0)
);